import { DomHashComparisonResult } from './index';
import pkg from '../../package.json';

export function formatAsHTML(result: DomHashComparisonResult): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>DOM Hash Comparison</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 2em; background: #f9f9f9; color: #222; }
    h2 { border-bottom: 2px solid #ccc; padding-bottom: 0.2em; }
    .version { font-size: 0.9em; color: #666; margin-top: -1em; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 2em; }
    th, td { padding: 0.5em 1em; border-bottom: 1px solid #ddd; text-align: left; }
    code { background: #eee; padding: 0.2em 0.4em; border-radius: 4px; }
    pre { background: #333; color: #f8f8f2; padding: 1em; overflow-x: auto; border-radius: 5px; }
    .add { color: #0c0; }
    .del { color: #c00; }
    .footer { margin-top: 2em; font-size: 0.9em; color: #777; }
  </style>
</head>
<body>
  <h2>DOM Hash Comparison</h2>
  <div class="version">Version: ${pkg.version}</div>
  <table>
    <tr><th>SHA A</th><td><code>${result.hashA}</code></td></tr>
    <tr><th>SHA B</th><td><code>${result.hashB}</code></td></tr>
    <tr><th>Structural Similarity</th><td>${(result.similarity * 100).toFixed(2)}%</td></tr>
    ${result.shapeSimilarity != null ? `<tr><th>Shape Similarity</th><td>${(result.shapeSimilarity * 100).toFixed(2)}%</td></tr>` : ''}
  </table>
  ${result.diff?.length ? `<h3>Structural Diff</h3><pre><code>${result.diff.map(line => {
    if (line.startsWith('+')) return `<span class='add'>${line}</span>`;
    if (line.startsWith('-')) return `<span class='del'>${line}</span>`;
    return line;
  }).join('\n')}</code></pre>` : ''}
  <div class="footer">
    Generated by <a href="https://www.npmjs.com/package/@iocium/domhash">@iocium/domhash</a><br>
    <em>Disclaimer: Similarity and resilience scores are heuristic and may not reflect all visual or behavioral aspects of a web page.</em>
  </div>
</body>
</html>`;
}