import { DomHashComparisonResult } from './index';
import pkg from '../../package.json';

export function formatAsMarkdown(result: DomHashComparisonResult): string {
  const lines = [
    `### DOM Hash Comparison Report`,
    `\n_Version: ${pkg.version}_`,
    `\n**SHA A:** \`${result.hashA}\``,
    `**SHA B:** \`${result.hashB}\``,
    `**Structural Similarity:** \`${(result.similarity * 100).toFixed(2)}%\``
  ];

  if (result.shapeSimilarity != null) {
    lines.push(`**Shape Similarity:** \`${(result.shapeSimilarity * 100).toFixed(2)}%\``);
  }

  if (result.diff?.length) {
    lines.push(`\n**Structural Diff:**\n`);
    lines.push('```diff');
    lines.push(...result.diff);
    lines.push('```');
  }

  lines.push(
    `\n---`,
    `Generated by [@iocium/domhash](https://www.npmjs.com/package/@iocium/domhash)`,
    `_Disclaimer: Similarity and resilience scores are heuristic and may not reflect all visual or behavioral aspects of a web page._`
  );

  return lines.join('\n');
}